# Attention, this is a template that is run through envsubst, but with a specific list of variables to replace. Thus:
# - HOOK_KERNEL_IMAGE: ${HOOK_KERNEL_IMAGE}
# - HOOK_KERNEL_ID: ${HOOK_KERNEL_ID}
# - Other variables are not replaced: for example this is a literal dollarsign-SOMETHING: $SOMETHING and with braces: ${SOMETHING}

kernel:
  image: "${HOOK_KERNEL_IMAGE}"
  cmdline: "this_is_not_used=at_at_all_in_hook command_line_is_determined_by=ipxe"

init:
  - linuxkit/init:45a1ad5919f0b6acf0f0cf730e9434abfae11fe6
  - linuxkit/runc:6062483d748609d505f2bcde4e52ee64a3329f5f
  - linuxkit/containerd:e7a92d9f3282039eac5fb1b07cac2b8664cbf0ad
  - linuxkit/ca-certificates:5aaa343474e5ac3ac01f8b917e82efb1063d80ff

onboot:
  - name: sysctl
    image: linuxkit/sysctl:5a374e4bf3e5a7deeacff6571d0f30f7ea8f56db

  - name: sysfs
    image: linuxkit/sysfs:ec174e06ca756f492e7a3fd6200d5c1672b97511

  - name: vlan
    image: linuxkit/ip:bb250017b05de5e16ac436b1eb19a39c87b5a252
    binds.add:
      - /etc/ip/vlan.sh:/etc/ip/vlan.sh
    command: [ "/etc/ip/vlan.sh" ]

services:
  - name: mdev
    image: quay.io/tinkerbell/hook-mdev:latest
    command: [ "mdev", "-v", "-S", "-df" ]
    capabilities:
      - all
    binds:
      - /dev/:/dev/
      - /lib/modules:lib/modules
    rootfsPropagation: shared
    devices:
      - path: all
        type: b

  - name: getty
    image: linuxkit/getty:5d86a2ce2d890c14ab66b13638dcadf74f29218b
    binds.add:
      - /etc/profile.d/local.sh:/etc/profile.d/local.sh
      - /etc/motd:/etc/motd
      - /etc/os-release:/etc/os-release
    env:
      - INSECURE=true

  - name: rngd
    image: linuxkit/rngd:cdb919e4aee49fed0bf6075f0a104037cba83c39

  - name: dhcpcd
    image: linuxkit/dhcpcd:e9e3580f2de00e73e7b316a007186d22fea056ee
    command: [ "/etc/ip/dhcp.sh", "false" ]
    binds.add:
      - /var/lib/dhcpcd:/var/lib/dhcpcd
      - /run:/run
      - /etc/ip/dhcp.sh:/etc/ip/dhcp.sh
      - /dhcpcd.conf:/dhcpcd.conf
    runtime:
      mkdir:
        - /var/lib/dhcpcd

  - name: ntpd
    image: linuxkit/openntpd:c90c6dd90f5dfb0ca71a73aac2dad69c8d956af3
    binds:
      - /var/run:/var/run

  - name: hook-docker
    image: quay.io/tinkerbell/hook-docker:latest
    capabilities:
      - all
    net: host
    pid: host
    mounts:
      - type: cgroup
        options: [ "rw", "nosuid", "noexec", "nodev", "relatime" ]
    binds:
      - /dev/console:/dev/console
      - /dev:/dev
      - /etc/resolv.conf:/etc/resolv.conf
      - /lib/modules:/lib/modules
      - /var/run/docker:/var/run
      - /var/run/images:/var/lib/docker
      - /var/run/worker:/worker
    runtime:
      mkdir:
        - /var/run/images
        - /var/run/docker
        - /var/run/worker

  - name: hook-bootkit
    image: quay.io/tinkerbell/hook-bootkit:latest
    capabilities:
      - all
    net: host
    mounts:
      - type: cgroup
        options: [ "rw", "nosuid", "noexec", "nodev", "relatime" ]
    binds:
      - /var/run/docker:/var/run
    runtime:
      mkdir:
        - /var/run/docker

#dbg  - name: sshd
#dbg    image: linuxkit/sshd:666b4a1a323140aa1f332826164afba506abf597

files:
  - path: etc/profile.d/local.sh
    contents: |
      alias       docker='ctr -n services.linuxkit tasks exec --tty --exec-id cmd hook-docker docker'
      alias docker-shell='ctr -n services.linuxkit tasks exec --tty --exec-id shell hook-docker sh'
      name_version=$(grep PRETTY_NAME= /etc/os-release | cut -d'=' -f2 | tr -d '"')
      export PS1='${name_version}:\w\$ '
      # Disable kernel messages on console
      # rpardini: why? # echo 4 > /proc/sys/kernel/printk
    mode: "0644"

  - path: etc/motd
    mode: "0644"
    # This is ANSI Regular font
    contents: |
      Welcome to HookOS! Your Tinkerbell operating system installation environment.

      ██   ██                   ██       ██████  ███████
      ██   ██  ██████   ██████  ██  ██  ██    ██ ██
      ███████ ██    ██ ██    ██ █████   ██    ██ ███████
      ██   ██ ██    ██ ██    ██ ██  ██  ██    ██      ██
      ██   ██  ██████   ██████  ██   ██  ██████  ███████

      - This Hook is using kernel ${HOOK_KERNEL_ID}
      - Use `docker` commands to access the tink worker/agent container and workflow action containers.
      - Logs are located in the `/var/log/` directory.

  - path: etc/os-release
    mode: "0444"
    contents: |
      NAME="HookOS"
      VERSION=0.8.1
      ID=hookos
      VERSION_ID=0.8.1
      PRETTY_NAME="HookOS 0.8.1"
      ANSI_COLOR="1;34"
      HOME_URL="https://github.com/tinkerbell/hook"

  - path: etc/ip/vlan.sh
    source: "files/vlan.sh"
    mode: "0777"

  - path: etc/ip/dhcp.sh
    source: "files/dhcp.sh"
    mode: "0777"

  - path: dhcpcd.conf
    source: "files/dhcpcd.conf"
    mode: "0644"

#dbg  - path: root/.ssh/authorized_keys
#dbg    source: ~/.ssh/id_rsa.pub
#dbg    mode: "0600"
#dbg    optional: true

trust:
  org:
    - linuxkit
    - library
